### ISSUE TITLE
Performance enhancements for chain indexing

### ISSUE THREAD

**Issue by neekolas** [xmtp/xmtpd#315]
```[tasklist]
### Tasks
- [x] Investigate blockchain indexing, shovel and rindexer, other 3rd party alternatives
- [x] Write Indexer enhancement proposal
- [ ] https://github.com/xmtp/xmtpd/issues/322
- [ ] https://github.com/xmtp/xmtpd/issues/323
- [ ] https://github.com/xmtp/xmtpd/issues/324
- [ ] https://github.com/xmtp/xmtpd/issues/325
```

**Comment by fbac** [comment]
Closing this as it will be worked out in different issues. Also, the new issues are added now to the replication tracking task.
