### ISSUE TITLE
Tracking: XMTPD Alpha

### ISSUE THREAD

**Issue by m-005** [xmtp/xmtpd#47]
```[tasklist]
### Tasks
- [ ] https://github.com/xmtp-labs/hq/issues/881
- [ ] https://github.com/xmtp/xmtpd/pull/15
- [ ] https://github.com/xmtp/xmtpd/pull/16
- [ ] https://github.com/xmtp/xmtpd/pull/17
- [ ] https://github.com/xmtp/xmtpd/pull/33
- [ ] https://github.com/xmtp/xmtpd/issues/48
- [ ] https://github.com/xmtp/xmtpd/issues/49
- [ ] https://github.com/xmtp/xmtpd/issues/50
- [ ] https://github.com/xmtp/xmtpd/issues/51
- [ ] https://github.com/xmtp/xmtpd/issues/52
- [ ] https://github.com/xmtp/xmtpd/issues/53
- [ ] https://github.com/xmtp/xmtpd/issues/54
- [ ] https://github.com/xmtp/xmtpd/issues/56
- [ ] https://github.com/xmtp/xmtpd/issues/57
- [ ] https://github.com/xmtp/xmtpd/issues/58
- [ ] https://github.com/xmtp/xmtpd/issues/61
- [ ] https://github.com/xmtp/xmtpd/issues/62
- [ ] https://github.com/xmtp/xmtpd/issues/63
- [ ] https://github.com/xmtp/xmtpd/issues/59
- [ ] https://github.com/xmtp/xmtpd/issues/60
- [ ] https://github.com/xmtp/xmtpd/issues/71
- [ ] https://github.com/xmtp/xmtpd/issues/65
```
